version: 0.2

proxy:
  logs: yes

env:
  variables:
    AWS_DEFAULT_REGION: ap-southeast-2


phases:
  install:
    commands:
      - npm -v
      - sudo npm install yarn -g
      - yarm -v

  build:
    commands:
      - cd flask-docker-app
