version: 0.2

proxy:
  logs: yes

env:
  variables:
    AWS_DEFAULT_REGION: ap-southeast-2


phases:
  install:
    commands:
      - npm -v
      - npm install yarn -g
      - yarn -v
      - npm install -g aws-cdk
      - cdk --help
      - export AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output=text)
      - pwd
      - ls -ltr
      - npm install -g typescript
      - cdk bootstrap aws://${AWS_ACCOUNT_ID}/${AWS_DEFAULT_REGION}
      - cdk diff
      - cdk deploy

  build:
    commands:
      - cd flask-docker-app
