apiVersion: v1
kind: Service
metadata: 
  name: flask-svc
spec: 
  selector: 
    app: flask
  ports:
    - name: web
      port: 80
      targetPort: 5000
  type: LoadBalancer
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    run: flask
  name: flask
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: pahud/amazon-ecs-flask-sample:latest
        ports:
          - containerPort: 5000
        resources:
          limits: 
            memory: "500Mi"
            cpu: "0.25"
---
apiVersion: v1
kind: Service
metadata: 
  name: flask-svc-green
spec: 
  selector: 
    app: flask-green
  ports:
    - name: web
      port: 80
      targetPort: 5000
  type: LoadBalancer
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    run: flask-green
  name: flask-green
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: flask-green
    spec:
      containers:
      - name: flask
        image: pahud/amazon-ecs-flask-sample:latest
        ports:
          - containerPort: 5000
        resources:
          limits: 
            memory: "500Mi"
            cpu: "0.25"
