apiVersion: v1
kind: Service
metadata:
  name: flask-svc
spec:
  selector:
    app: flask
  ports:
    - name: web
      port: 80
      targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: flask
  name: flask-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
        - name: flask
          image: public.ecr.aws/pahudnet/flask-docker-sample
          ports:
            - containerPort: 80
          # command:
          #   - "sh"
          #   - "-c"
          #   - "yum install -y python3-pip && tail -f /var/log/yum.log "
          resources:
            limits:
              memory: "500Mi"
              cpu: "0.25"
